### ISSUE TITLE
Футер бы прижать к низу

### ISSUE THREAD

**Issue by NikolayVolkovR** [denisgaker/EPAM_homework#1]
https://github.com/denisgaker/EPAM_homework/blob/19e60813ea91de8d6c5690388f37d118df892875/src/App.tsx#L47

![Uploading image.png…]()

**Comment by denisgaker** [comment]
Прижал. Для страниц, где сразу после header идёт тег h1 (без родительского блока) добавил min-height.

**Comment by denisgaker** [comment]
Переделал стили, прижимающие футер к низу на flex.
