### ISSUE TITLE
Структура проекта

### ISSUE THREAD

**Issue by NikolayVolkovR** [denisgaker/EPAM_homework#10]
https://github.com/denisgaker/EPAM_homework/blob/19e60813ea91de8d6c5690388f37d118df892875/src/App.tsx#L1

![image](https://user-images.githubusercontent.com/28064446/140309057-06cdf83d-5994-43c4-929a-fab7c388bf5c.png)

Хорошо бы сгруппировать папки с компонентами.
Например подчёркнутые можно вынести в src/components/

**Comment by denisgaker** [comment]
Вынес подчёркнутые папки в src/components
