### ISSUE TITLE
Тип в дженерик

### ISSUE THREAD

**Issue by NikolayVolkovR** [denisgaker/EPAM_homework#12]
https://github.com/denisgaker/EPAM_homework/blob/19e60813ea91de8d6c5690388f37d118df892875/src/header/header/Header.tsx#L5

Давай чуть красивее и компактнее сделаем 
`export const Header: React.FC<{}> = (props: HeaderProps)`
=>
```
export const Header:FC<HeaderProps> = ({children}) => (
  <header className="header">{children}</header>
);
```
Аналогично для остальных компонентов

**Comment by denisgaker** [comment]
Конкретно в Header.tsx тип вообще убран за ненадобностью, в остальных компонентах типы перенесены в дженерик, а из параметров убраны.
