### ISSUE TITLE
Childred уже есть в FC

### ISSUE THREAD

**Issue by NikolayVolkovR** [denisgaker/EPAM_homework#15]
https://github.com/denisgaker/EPAM_homework/blob/19e60813ea91de8d6c5690388f37d118df892875/src/header/header/Header.interface.ts#L6

В этом случае интерфейс вообще не нужен.

**Comment by denisgaker** [comment]
Удалил интерфейс и соответственно отредактировал Header.tsx, где этот интерфейс использовался.
