### ISSUE TITLE
Можно вынести socialNetworkLinks ближе к компоненту, который их использует?

### ISSUE THREAD

**Issue by NikolayVolkovR** [denisgaker/EPAM_homework#16]
https://github.com/denisgaker/EPAM_homework/blob/74e74804fbd3549fed74ce166d635798c78d51f4/src/Data.ts#L10

**Comment by denisgaker** [comment]
Вынес данные в константы по компонентам для: App, SocLinks, Search, SearchBy, SearchBtns

**Comment by NikolayVolkovR** [comment]
Всё ещё есть поле socialNetworkLinks в Data.ts
