### ISSUE TITLE
Если разнести данные по файлам констант для конкретных компонентов, то типизация вообще не нужна

### ISSUE THREAD

**Issue by NikolayVolkovR** [denisgaker/EPAM_homework#18]
https://github.com/denisgaker/EPAM_homework/blob/74e74804fbd3549fed74ce166d635798c78d51f4/src/Data.ts#L3

например
/src/components/App/app.constants.ts
export const APP_NAME = "HETflix";

**Comment by denisgaker** [comment]
Вроде в первых лекциях говорилось, что в компонентах не должно быть никаких конкретных данных.

**Comment by denisgaker** [comment]
Вынес данные в константы по компонентам для: App, SocLinks, Search, SearchBy, SearchBtns
