### ISSUE TITLE
С большой буквы обычно называют react компоненты и классы. Почему эта переменная с большой, не понял

### ISSUE THREAD

**Issue by NikolayVolkovR** [denisgaker/EPAM_homework#2]
https://github.com/denisgaker/EPAM_homework/blob/19e60813ea91de8d6c5690388f37d118df892875/src/App.tsx#L16

**Comment by denisgaker** [comment]
Исправил в App.tsx ( + добавил export default в Data.ts и соответственно заменил импорт)

**Comment by denisgaker** [comment]
Для обычных констант исправил названия (с маленькой буквы) в App.txs, Soclinks.tsx, constants.ts).
