### ISSUE TITLE
Всё ещё есть поле socialNetworkLinks в Data.ts

### ISSUE THREAD

**Issue by NikolayVolkovR** [denisgaker/EPAM_homework#21]
Всё ещё есть поле socialNetworkLinks в Data.ts

_Originally posted by @NikolayVolkovR in https://github.com/denisgaker/EPAM_homework/issues/16#issuecomment-962618462_

**Comment by denisgaker** [comment]
Удалил Data.ts и Data.types.ts, они уже нигде не используются.
