### ISSUE TITLE
MovieList & MovieList2

### ISSUE THREAD

**Issue by NikolayVolkovR** [denisgaker/EPAM_homework#23]
https://github.com/denisgaker/EPAM_homework/blob/c1801f9631868cf80f01d6026e0fad1a47f1cfc3/src/components/content/MovieList.tsx#L1

Нужно дать имя, из которого было бы понятно чем компоненты отличаются.

**Comment by NikolayVolkovR** [comment]
Если первый просто для истории, то его надо удалить из репозитория.

**Comment by denisgaker** [comment]
Удалил MovieList, он был написан на классах в рамках задачи по errorBoundary.

MovieList2 переименовал в MovieList.
