### ISSUE TITLE
Можно вынести в константы.

### ISSUE THREAD

**Issue by NikolayVolkovR** [denisgaker/EPAM_homework#24]
https://github.com/denisgaker/EPAM_homework/blob/c1801f9631868cf80f01d6026e0fad1a47f1cfc3/src/components/content/MovieList2.tsx#L20

Каждый раз при ререндере компонента будет создаваться новый массив.

**Comment by denisgaker** [comment]
Вынес в файл src/components/content/movieList.constants.ts
