### ISSUE TITLE
searchParamsFromUrl[3], searchParamsFromUrl[1]

### ISSUE THREAD

**Issue by NikolayVolkovR** [denisgaker/EPAM_homework#25]
https://github.com/denisgaker/EPAM_homework/blob/c1801f9631868cf80f01d6026e0fad1a47f1cfc3/src/components/content/MovieList2.tsx#L29

От "магических" элементов надо бы избавиться и дать им осознанные имена. 
Почему бы не воспользоваться готовым решением? https://www.npmjs.com/package/url-parse

**Comment by denisgaker** [comment]
Переделал с использованием url-parse, сократил название объекта для параметров (был searchParamsFromUrl, стал urlParams).
