### ISSUE TITLE
Такие штуки лучше вынести в файл с константами и дать соответствующие имена

### ISSUE THREAD

**Issue by NikolayVolkovR** [denisgaker/EPAM_homework#3]
https://github.com/denisgaker/EPAM_homework/blob/19e60813ea91de8d6c5690388f37d118df892875/src/App.tsx#L17

src/components/app/app.constants.ts
или не в app, а куда по логике правильнее
если межкомпонентные константы, то в какую-нибудь папку типа src/components/common/constants.ts

export const SEARCH_CTA = "..."

**Comment by NikolayVolkovR** [comment]
А, так три штуки к Search относятся - туда их и поместить )
Делать общий файл - не очень хорошо, т.к. сложнее читать (понимать).

**Comment by denisgaker** [comment]
Вынес константы в components/header/search/constants.ts и импортировал оттуда.
