### ISSUE TITLE
Пагинацию бы в отдельный компонент

### ISSUE THREAD

**Issue by NikolayVolkovR** [denisgaker/EPAM_homework#32]
https://github.com/denisgaker/EPAM_homework/blob/c1801f9631868cf80f01d6026e0fad1a47f1cfc3/src/components/content/MovieList2.tsx#L65

И `onClick={() => fetchMovies(p, limit, searchParamsFromUrl[3], searchParamsFromUrl[1])}` давай вынесем в хэндлер.

**Comment by denisgaker** [comment]
Вынес в src/components/pagination/pagination.tsx (с собственным style.js).
