### ISSUE TITLE
Разве, auto не по умолчанию?

### ISSUE THREAD

**Issue by NikolayVolkovR** [denisgaker/EPAM_homework#33]
https://github.com/denisgaker/EPAM_homework/blob/c1801f9631868cf80f01d6026e0fad1a47f1cfc3/src/components/content/style.css#L2

**Comment by denisgaker** [comment]
Удалил 
src/components/movies/style.css
src/components/header/style.css
src/components/footer/style.css
Они уже не используются.
Проверил файлы с jss-стилями на height: auto.
