### ISSUE TITLE
Тут правда нужно так сложно? Если да,  501 хорошо бы вынести в переменную.

### ISSUE THREAD

**Issue by NikolayVolkovR** [denisgaker/EPAM_homework#34]
https://github.com/denisgaker/EPAM_homework/blob/c1801f9631868cf80f01d6026e0fad1a47f1cfc3/src/components/content/style.css#L3

**Comment by denisgaker** [comment]
Это я прижимал футер к нижней части экрана.
Сейчас сделано с помощью flex.
