### ISSUE TITLE
Порядок путей в роутах

### ISSUE THREAD

**Issue by NikolayVolkovR** [denisgaker/EPAM_homework#4]
https://github.com/denisgaker/EPAM_homework/blob/19e60813ea91de8d6c5690388f37d118df892875/src/App.tsx#L33

Можно и так, т.е. первым указать '/'. Однако принято ставить "чем короче, тем ниже". Таким образом он будет последним. 
Т.е. сперва пишем более детализированные роуты с большим количеством параметров и т.д. Роутер выберет первый, который сматчит с текущей query string.

**Comment by denisgaker** [comment]
Исправил по принципу "чем короче, тем ниже". Единственное - оставил Redirect в самом низу, т.к. он вроде как не совсем Route.
