### ISSUE TITLE
Имеет смысл для display: inline?

### ISSUE THREAD

**Issue by NikolayVolkovR** [denisgaker/EPAM_homework#40]
https://github.com/denisgaker/EPAM_homework/blob/c1801f9631868cf80f01d6026e0fad1a47f1cfc3/src/components/content/style.css#L26

**Comment by denisgaker** [comment]
Имеет, если не обозначить ширину, ширина установится по содержимому. Когда содержимого много, это не заметно, а когда мало, не будут работать выравнивания (в нашем случае это касается заголовков карточек с фильмами и span'ов с жанрами и датой выхода).
