### ISSUE TITLE
Лишние свойства

### ISSUE THREAD

**Issue by NikolayVolkovR** [denisgaker/EPAM_homework#43]
https://github.com/denisgaker/EPAM_homework/blob/c1801f9631868cf80f01d6026e0fad1a47f1cfc3/src/components/content/style.css#L74

```
border-top: 1px solid #ff0000;
border-bottom: 1px solid #ff0000;
border-left: 1px solid #ff0000;
```

Как минимум, можно вынести в переменную.

Или так:
```
border: 1px solid #ff0000;
border-right: none;
```

**Comment by denisgaker** [comment]
Исправил.
