### ISSUE TITLE
Группировка свойст

### ISSUE THREAD

**Issue by NikolayVolkovR** [denisgaker/EPAM_homework#44]
https://github.com/denisgaker/EPAM_homework/blob/c1801f9631868cf80f01d6026e0fad1a47f1cfc3/src/components/content/style.css#L72

.pagination .page встречается 5 раз.

Нельзя сгруппировать как-то так?

.pagination 
  .page {
    ...
   &:last-child {...}
   &.active {...}
  }
}

**Comment by denisgaker** [comment]
Переделано в jss, там это проблемы нет.
