### ISSUE TITLE
Слово Network нужно добавить в остальные файлы, либо удалить здесь

### ISSUE THREAD

**Issue by NikolayVolkovR** [denisgaker/EPAM_homework#54]
https://github.com/denisgaker/EPAM_homework/blob/c1801f9631868cf80f01d6026e0fad1a47f1cfc3/src/components/footer/socialNetworkLinks.types.ts#L1

**Comment by denisgaker** [comment]
Удалил файл socialNetworkLinks.types.ts, он уже нигде не используется.
