### ISSUE TITLE
Вынести моки и стабы

### ISSUE THREAD

**Issue by NikolayVolkovR** [denisgaker/EPAM_homework#6]
https://github.com/denisgaker/EPAM_homework/blob/19e60813ea91de8d6c5690388f37d118df892875/src/Data.ts#L89

Если эти моки где-то используются, то лучше их вынести в соответствующее место

**Comment by denisgaker** [comment]
movies теперь приходят с сервера, удалил их и соответствующие интерфрейсы, типы и enum'ы.
