### ISSUE TITLE
Header & Heading

### ISSUE THREAD

**Issue by NikolayVolkovR** [denisgaker/EPAM_homework#61]
https://github.com/denisgaker/EPAM_homework/blob/c1801f9631868cf80f01d6026e0fad1a47f1cfc3/src/components/header/Header.tsx#L7

Компонент называется Header, а тестовый файл в той же папке Heading. С этим нужно что-то сделать.

**Comment by denisgaker** [comment]
Перенёс тестовый файл в папку heading (это тест для компонента Heading).
