### ISSUE TITLE
В один компонент

### ISSUE THREAD

**Issue by NikolayVolkovR** [denisgaker/EPAM_homework#68]
https://github.com/denisgaker/EPAM_homework/blob/c1801f9631868cf80f01d6026e0fad1a47f1cfc3/src/components/header/search/Search.tsx#L30

Можно всё это вынести в <SearchBy /> ?

```
<div className={classes.searchBy}>
  <span>Search by</span>
  <SearchBy />
</div>
```

**Comment by denisgaker** [comment]
Вынес
