### ISSUE TITLE
Переместить типы

### ISSUE THREAD

**Issue by NikolayVolkovR** [denisgaker/EPAM_homework#7]
https://github.com/denisgaker/EPAM_homework/blob/19e60813ea91de8d6c5690388f37d118df892875/src/Data.ts#L23

Типы нужно разнести по папочкам ближе к местам их использования. Хранить вместе, не очень хорошая практика.

**Comment by denisgaker** [comment]
Переместил. Общие типы лежат в 
src/Datats.types.ts
типы для иконок-ссылок на социальные сети лежат в 
src/components/footer/socialNetworkLinks.types.ts
