### ISSUE TITLE
mainType => MainType

### ISSUE THREAD

**Issue by NikolayVolkovR** [denisgaker/EPAM_homework#9]
https://github.com/denisgaker/EPAM_homework/blob/19e60813ea91de8d6c5690388f37d118df892875/src/Data.ts#L2

Нужно пройтись по нэймингу остальных элементов с учётом предыдущих комментов.

**Comment by denisgaker** [comment]
Нейминг был исправлен в рамках задачи по ESLint airbnb, сейчас всё в PascalCase.
Кроме констант. Их переименовал в camelCase (первая буква строчная).
